const ActionTypes = {
  FETCH_PROMO_CARD_REQUEST: `FETCH_PROMO_CARD_REQUEST`,
  FETCH_PROMO_CARD_SUCCESS: `FETCH_PROMO_CARD_SUCCESS`,
  FETCH_PROMO_CARD_FAILURE: `FETCH_PROMO_CARD_FAILURE`,
  FETCH_CARDS_REQUEST: `FETCH_CARDS_REQUEST`,
  FETCH_CARDS_SUCCESS: `FETCH_CARDS_SUCCESS`,
  FETCH_CARDS_FAILURE: `FETCH_CARDS_FAILURE`,
  FETCH_REVIEWS_REQUEST: `FETCH_REVIEWS_REQUEST`,
  FETCH_REVIEWS_SUCCESS: `FETCH_REVIEWS_SUCCESS`,
  FETCH_REVIEWS_FAILURE: `FETCH_REVIEWS_FAILURE`,
  CHANGE_GENRE: `CHANGE_GENRE`,
  CHANGE_SHOWING_CARDS_AMOUNT: `CHANGE_SHOWING_CARDS_AMOUNT`,
  CHANGE_SELECTED_CARD: `CHANGE_SELECTED_CARD`,
  SET_DEFAULT_FILTERED_CARD_LIST: `SET_DEFAULT_FILTERED_CARD_LIST`,
  FETCH_AUTH_REQUEST: `FETCH_AUTH_REQUEST`,
  FETCH_AUTH_SUCCESS: `FETCH_AUTH_SUCCESS`,
  FETCH_AUTH_FAILURE: `FETCH_AUTH_FAILURE`,
};

export default ActionTypes;
