const ActionTypes = {
  FETCH_PROMO_CARD_REQUEST: `FETCH_PROMO_CARD_REQUEST`,
  FETCH_CARDS_REQUEST: `FETCH_CARDS_REQUEST`,
  FETCH_PROMO_CARD_SUCCESS: `FETCH_PROMO_CARD_SUCCESS`,
  FETCH_CARDS_SUCCESS: `FETCH_CARDS_SUCCESS`,
  FETCH_PROMO_CARD_FAILURE: `FETCH_PROMO_CARD_FAILURE`,
  FETCH_CARDS_FAILURE: `FETCH_CARDS_FAILURE`,
  CHANGE_GENRE: `CHANGE_GENRE`,
  CHANGE_FILTERED_CARDS: `CHANGE_FILTERED_CARDS`,
  CHANGE_SHOWING_CARDS_AMOUNT: `CHANGE_SHOWING_CARDS_AMOUNT`,
};

export default ActionTypes;
