const ActionTypes = {
  CARDS_LOADED: `CARDS_LOADED`,
  PROMO_CARD_LOADED: `PROMO_CARD_LOADED`,
  CHANGE_GENRE: `CHANGE_GENRE`,
  CHANGE_FILTERED_CARDS_LENGTH: `CHANGE_FILTERED_CARDS_LENGTH`,
  CHANGE_SHOWING_CARDS_AMOUNT: `CHANGE_SHOWING_CARDS_AMOUNT`,
};

export default ActionTypes;
